// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addTabButton': string;
  'addTabContainer': string;
  'removeTabButton': string;
  'tabContent': string;
  'tabFooter': string;
  'tabPanel': string;
  'tabWrapper': string;
  'toggleDocumentType': string;
}
export const cssExports: CssExports;
export default cssExports;
